# "/admin/sniff.jsp": "https://run.mocky.io/v3/6613f69c-65cf-44d4-b29c-7887f21cfd59",
#     "/api/npx-service": "https://run.mocky.io/v3/84643c67-6ddb-4cf1-8141-f637154c9520",
#     "/pmg/nxn-metrics": "https://run.mocky.io/v3/b6a301fc-64d8-497d-9138-058d8946bd70",
#     "/app/nxn-resource-cache": "https://run.mocky.io/v3/34a9aeba-0b71-4fac-8451-b122c50cce45",
#     "/api/nxn-navbar-service": "https://run.mocky.io/v3/8f5cd8a1-85ae-4d73-946b-59dda7ce5992"

# [endpoints]
#  "/admin/sniff.jsp" = "https://run.mocky.io/v3/6613f69c-65cf-44d4-b29c-7887f21cfd59"