[package]
org = "xyz"
name = "xyz_gateway"
version = "0.1.0"
distribution = "2201.5.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "gateway"
version = "0.1.0"
repository = "local"

[[platform.java11.dependency]]
groupId = "com.hazelcast"
artifactId = "hazelcast"
version = "5.2.3"
