# Global plugins
[[ballerinax.gateway.requestPlugins]]
id = "AddHeadersPlugin"
config = {appId = "xyz-app"}

[[ballerinax.gateway.responsePlugins]]
id = "RemoveHeadersPlugin"
config = {appId = "xyz-app"}

# Application 1 
[[ballerinax.gateway.apps]]
basePath = "/app/xyz-resource-cache"
endpointUrl = "https://run.mocky.io/v3/34a9aeba-0b71-4fac-8451-b122c50cce45"

[[ballerinax.gateway.apps.requestPlugins]]
id = "AddAccessTokenPlugin"

# Application 2
[[ballerinax.gateway.apps]]
basePath = "/api/xyz-navbar-service"
endpointUrl = "https://run.mocky.io/v3/8f5cd8a1-85ae-4d73-946b-59dda7ce5992"

[[ballerinax.gateway.apps.requestPlugins]]
id = "CORSHeaderPlugin"

[[ballerinax.gateway.apps.requestPlugins]]
id = "NetworkControlPlugin"
config = {level = "2"}

[[ballerinax.gateway.apps.requestPlugins]]
id = "AddAccessTokenPlugin"

# Application 3
[[ballerinax.gateway.apps]]
basePath = "/api/xyz-entitlement-service"
endpointUrl = "https://run.mocky.io/v3/6613f69c-65cf-44d4-b29c-7887f21cfd59"

[[ballerinax.gateway.apps.requestPlugins]]
id = "NetworkControlPlugin"
config = {level = "2"}

[[ballerinax.gateway.apps.requestPlugins]]
id = "HazelcastMapClientPlugin"

[[ballerinax.gateway.apps.responsePlugins]]
id = "RemoveHeadersPlugin"

[[ballerinax.gateway.apps.responsePlugins]]
id = "HazelcastMapClientPlugin"

# Application 4
[[ballerinax.gateway.apps]]
basePath = "/api/xyz-entitlement-service/metrics"
endpointUrl = "https://run.mocky.io/v3/b6a301fc-64d8-497d-9138-058d8946bd70"

# Application 5
[[ballerinax.gateway.apps]]
basePath = "/api/xyz-service"
endpointUrl = "https://run.mocky.io/v3/84643c67-6ddb-4cf1-8141-f637154c9520"

# Application 6
[[ballerinax.gateway.apps]]
basePath = "/api"
endpointUrl = "https://run.mocky.io/v3/34a9aeba-0b71-4fac-8451-b122c50cce45"

[[ballerinax.gateway.apps.requestPlugins]]
id = "AlwaysAbortPlugin"

[ballerina.log]
level = "DEBUG"
